#!/bin/bash

caller_directory=$(pwd)

gitignore_contents=`cat <<EOF
# If you prefer the allow list template instead of the deny list, see community template:
# https://github.com/github/gitignore/blob/main/community/Golang/Go.AllowList.gitignore
#
# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with go test -c
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

# Dependency directories (remove the comment below to include it)
# vendor/

# Go workspace file
go.work
go.work.sum

# env file
.env
EOF
`

if [ ! -e ".gitignore" ]; then
  echo "$gitignore_contents" > .gitignore
else
  echo ".gitignore already existed so it was not recreated"
fi
