
# To use any of these aliases with neovim command mode, you have to create a ~/.zshenv file instead of .zshrc.

export PATH="$PATH:/Users/rase/Library/Application Support/JetBrains/Toolbox/scripts"

export PATH="$PATH:/Users/rase/go/bin"

export PATH="$PATH:/Users/rase/.config/dotfiles/nvim/scripts"

alias vim='nvim'
alias ac='source /Users/rase/.zprofile; source /Users/rase/.zshrc; tmux source ~/.tmux.conf'

alias dev='cd /Users/rase/dev'

alias tori_scraper='cd /Users/rase/dev/tori_scraper'

alias tori_backend='cd /Users/rase/dev/toripro'

alias tori_frontend='cd /Users/rase/dev/tori_ui_next'

alias scrapelite='cd /Users/rase/dev/scrapelite'

alias dot='cd /Users/rase/.config/dotfiles'

alias todo='/Users/rase/.config/dotfiles/zsh/todo.sh'

alias ide='/Users/rase/.config/dotfiles/zsh/ide.sh'

alias view='nvim -R'
alias v='nvim -R'

alias godoc='/usr/local/go/src'

alias golib='~/go/pkg/mod/github.com'

alias links='vim ~/links.md'

alias tp="docker run --cap-add=NET_ADMIN -ti --rm -v $(pwd):/apps -w /apps alpine/ansible ansible-playbook"

# case insensitive grepping with line numbers to jump to in nvim buffer with gF
# there is a version of this that pipes the output into neovim for ease of use
# in the shell script named gn (grep - neovim)
alias g='rg -in'

alias gn='/Users/rase/.config/dotfiles/zsh/gn'

alias b='make build'
alias r='make run'

eval "$(/opt/homebrew/bin/brew shellenv)"

# Created by `pipx` on 2025-06-30 14:18:35
export PATH="$PATH:/Users/rase/.local/bin"
