

export PATH="$PATH:/Users/rase/Library/Application Support/JetBrains/Toolbox/scripts"

export PATH="$PATH:/Users/rase/go/bin"

export PATH="$PATH:/Users/rase/.config/dotfiles/nvim/scripts"

alias vim='nvim'
alias ac='source /Users/rase/.zprofile; source /Users/rase/.zshrc; tmux source ~/.tmux.conf'

alias dev='cd /Users/rase/dev'

alias tori_scraper='cd /Users/rase/dev/tori_scraper'

alias tori_backend='cd /Users/rase/dev/toripro'

alias tori_frontend='cd /Users/rase/dev/tori_ui_next'

alias scrapelite='cd /Users/rase/dev/scrapelite'

alias dot='cd /Users/rase/.config/dotfiles'

alias todo='/Users/rase/.config/dotfiles/zsh/todo.sh'

alias view='nvim -R'

alias godoc='/usr/local/go/src'

alias golib='~/go/pkg/mod/github.com'

eval "$(/opt/homebrew/bin/brew shellenv)"
